### ISSUE TITLE
Access to script at from origin 'null' has been blocked by CORS policy

### ISSUE THREAD

**Issue by sibbng** [egoist/esbuild-service#15]
Hi, looks like it doesn't allow requests from iframe srcdoc.

>Access to script at 'https://esbuild.vercel.app/preact/hooks' from origin 'null' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.

[Reproduction](https://esm.codes/#aW1wb3J0IHsgaCwgcmVuZGVyIH0gZnJvbSAiaHR0cHM6Ly9lc2J1aWxkLnZlcmNlbC5hcHAvcHJlYWN0IjsKaW1wb3J0IHsgdXNlU3RhdGUgfSBmcm9tICJodHRwczovL2VzYnVpbGQudmVyY2VsLmFwcC9wcmVhY3QvaG9va3MiOwppbXBvcnQgaHRtIGZyb20gImh0dHBzOi8vY2RuLnNreXBhY2suZGV2L2h0bSI7CmltcG9ydCB7CiAgZGVmaW5lQ29tcG9uZW50LAogIHJlZiwKICBjb21wdXRlZCwKICBvbk1vdW50ZWQsCiAgb25Vbm1vdW50ZWQsCn0gZnJvbSAiaHR0cHM6Ly9lc2J1aWxkLnZlcmNlbC5hcHAvcmVhY3RpdnVlQDAuNC4xL3ByZWFjdCI7Cgpjb25zdCBodG1sID0gaHRtLmJpbmQoaCk7Cgpjb25zdCBNeUNvdW50ZXIgPSBkZWZpbmVDb21wb25lbnQoCiAgLy8gc2V0dXAgZnVuY3Rpb24gaW4gVnVlCiAgKHByb3BzKSA9PiB7CiAgICBjb25zdCBjb3VudGVyID0gcmVmKHByb3BzLnZhbHVlKTsKICAgIGNvbnN0IGRvdWJsZWQgPSBjb21wdXRlZCgoKSA9PiBjb3VudGVyLnZhbHVlICogMik7CiAgICBjb25zdCBpbmMgPSAoKSA9PiAoY291bnRlci52YWx1ZSArPSAxKTsKCiAgICBvbk1vdW50ZWQoKCkgPT4gY29uc29sZS5sb2coIkNvdW50ZXIgbW91bnRlZCIpKTsKICAgIG9uVW5tb3VudGVkKCgpID0+IGNvbnNvbGUubG9nKCJDb3VudGVyIHVubW91bnRlZCIpKTsKCiAgICByZXR1cm4geyBjb3VudGVyLCBkb3VibGVkLCBpbmMgfTsKICB9LAogIC8vIGZ1bmN0aW9uYWwgY29tcG9uZW50IGluIHByZWFjdAogICh7IGNvdW50ZXIsIGRvdWJsZWQsIGluYyB9KSA9PiB7CiAgICAvLyB5b3UgY2FuIHVzZSBwcmVhY3QgaG9va3MgaGVyZQogICAgcmV0dXJuIGh0bWxgCiAgICAgIDxkaXY+CiAgICAgICAgPGRpdj4ke2NvdW50ZXJ9IHggMiA9ICR7ZG91YmxlZH08L2Rpdj4KICAgICAgICA8YnV0dG9uIG9uQ2xpY2s9JHtpbmN9PkluY3JlYXNlPC9idXR0b24+CiAgICAgIDwvZGl2PgogICAgYDsKICB9Cik7CgpmdW5jdGlvbiBBcHAoKSB7CiAgY29uc3QgW3Nob3csIHNldFNob3ddID0gdXNlU3RhdGUodHJ1ZSk7CgogIHJldHVybiBodG1sYAogICAgPGJ1dHRvbiBvbkNsaWNrPSR7KCkgPT4gc2V0U2hvdyghc2hvdyl9PgogICAgICAke3Nob3cgPyAiSGlkZSIgOiAiU2hvdyJ9IGNvdW50ZXIKICAgIDwvYnV0dG9uPgogICAgJHtzaG93ICYmIGh0bWxgPCR7TXlDb3VudGVyfSB2YWx1ZT0kezEwfSAvPmB9CiAgYAp9CgpyZW5kZXIoaHRtbGA8JHtBcHB9Lz5gLCBkb2N1bWVudC5ib2R5KTsKCmRvY3VtZW50LmJvZHkuYmdDb2xvciA9ICJ3aGl0ZSI=)

**Comment by sibbng** [comment]
> should work now

Yep cors issue fixed but it looks like bundles it inlines preact import within preact/hooks.

In my opinion it should import preact from https://esbuild.vercel.app/preact instead of inlining it.

**Comment by egoist** [comment]
yeah maybe peerDependecies should been excluded
